name: Alain Guillemain
favicon: null
layout_spectrum: 1
typography_spectrum: 0.77111
title: 'Alain Guillemain | Writer · Philosopher'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010e15'
    - '#f5f7f4'
    - '#373730'
    - '#e8c9aa'
    - '#8f6747'
  brandStrength: 0.3125
  lightness: 0.5625
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
